# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Github:
    url: https://github.com/xinhuagu/xinhuagu.github.io
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: 

# URL of the Home page image
index_cover: img/home-bg.jpg

# Default post title
default_post_title: Untitledtled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: xinhua
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/xinhuagu/xinhuagu.github.iolog
gitlab_url:
linkedin_url: https://www.linkedin.com/in/xinhua-gu/
mailto: xinhua.gu@gmail.com
